/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Head: typeof import('./components/Head.vue')['default']
    'IBasil:awardOutline': typeof import('~icons/basil/award-outline')['default']
    'ICarbon:alignBoxTopLeft': typeof import('~icons/carbon/align-box-top-left')['default']
    'ICarbon:language': typeof import('~icons/carbon/language')['default']
    'ICarbon:logout': typeof import('~icons/carbon/logout')['default']
    'ICarbon:modelAlt': typeof import('~icons/carbon/model-alt')['default']
    'ICarbon:userAvatarFilled': typeof import('~icons/carbon/user-avatar-filled')['default']
    'IMdi:codeJson': typeof import('~icons/mdi/code-json')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    LanguageButton: typeof import('./components/LanguageButton.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
